Prevent NPE when evaluating debugger expressions on partial states.
```java
Dec 17, 2025 10:19:04 AM org.eclipse.lsp4j.jsonrpc.RemoteEndpoint
fallbackResponseError
SEVERE: Internal error: Cannot invoke
"tlc2.tool.TLCState.lookup(util.UniqueString)" because "s" is null
java.lang.NullPointerException: Cannot invoke
"tlc2.tool.TLCState.lookup(util.UniqueString)" because "s" is null
	at tlc2.tool.impl.Spec.lookup(Spec.java:411)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:1838)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:117)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1732)
	at tlc2.tool.impl.FastTool.eval(FastTool.java:110)
	at tlc2.tool.impl.Tool.evalApplImpl(Tool.java:2658)
	at tlc2.tool.impl.FastTool.evalAppl(FastTool.java:117)
	at tlc2.tool.impl.Tool.evalImpl(Tool.java:1732)
	at tlc2.tool.impl.DebugTool.eval(DebugTool.java:174)
	at tlc2.value.impl.LazyValue.eval(LazyValue.java:394)
	at tlc2.value.impl.LazyValue.eval(LazyValue.java:390)
	at tlc2.value.impl.LazyValue.eval(LazyValue.java:386)
	at tlc2.debug.TLCStackFrame.lambda$11(TLCStackFrame.java:589)
	at tlc2.tool.impl.DebugTool.eval(DebugTool.java:626)
	at tlc2.debug.TLCStackFrame.unlazy(TLCStackFrame.java:588)
	at tlc2.debug.TLCStackFrame.getVariable(TLCStackFrame.java:433)
	at tlc2.debug.TLCStackFrame.get(TLCStackFrame.java:508)
	at tlc2.debug.TLCDebugger.lambda$4(TLCDebugger.java:301)
	at java.base/java.util.Optional.map(Optional.java:260)
	at tlc2.debug.TLCDebugger.evaluate(TLCDebugger.java:301)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$recursiveFindRpcMethods$0(GenericEndpoint.java:65)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.request(GenericEndpoint.java:128)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleRequest(RemoteEndpoint.java:271)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:201)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:185)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:97)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:114)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

[Bug][TLC][Debugger]

Signed-off-by: Markus Alexander Kuppe <github.com@lemmster.de>